name: build
on: pull_request
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       os: [ubuntu-latest]
       node: [20]
       exclude:
         - os: macos-latest
           node: 10
    steps:
     - name: my first step
       env:
         MY_VAR: Hi there! my name is
         FIRST_NAME: Byron
         MIDDLE_NAME: Edward
         LAST_NAME: Blank
       run: echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
     - name: my second step
       if: success()
       run: echo "The previous step has finished successfully"
     - name: my third step
       uses: actions/checkout@v1
       with: 
         node-version: 20
         registry-url: https://npm.pkg.github.com/
     - name: my fourth step
       uses: actions/first-interaction@v1
       with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
         issue-message: "Message that will be displayed on users first issue"
         pr-message: "message that will be dispalyed on users first pr"
      
  
         
       
         
    
