name: build
on: push
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       os: [macos-latest, windows-latest, ubuntu-latest]
       node: [16, 18, 20]
       exclude:
         - os: macos-latest
           node: 10
    steps:
     - name: my first step
       env:
         MY_VAR: Hi there! my name is
         FIRST_NAME: Byron
         MIDDLE_NAME: Edward
         LAST_NAME: Blank
       run: echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
  
         
       
         
    
